#!/usr/bin/env python3
# Copyright (c) 2026 Vincent Jardin, Vincent Cruz, Free Mobile
# SPDX-License-Identifier: BSD-4-Clause
"""Generate lan80xx_regs.h: MMD + register-address enums for lan80xx-spid.

Reads the flat ``g_lan80xx_regs[]`` table emitted by lan80xx_apps'
``gen_lan80xx_regs.py`` (itself derived from sw-mepa's regs_lan80xx_*.h)
and emits symbolic C enums only -- no runtime table:

  * one enum ``lan80xx_mmd_t`` mapping each MDIO Manageable Device name
    to its number (0x00..0x1F);
  * one enum per MMD mapping each register name to its address offset
    within that MMD.

Enumerator values are the raw offsets, so the mmd (device) and the addr
(offset) stay independent, matching the SPI instruction layout the
daemon builds (slice<<21 | mmd<<16 | addr).

Register names are kept verbatim (the canonical LAN80XX_ symbols from
sw-mepa) so they can be used as drop-in constants. All enumerators live
in one file scope, so a name that appears more than once (a handful of
aliases do) is emitted once; the duplicate is dropped with a note.

Usage:
    gen_lan80xx_regs_header.py <lan80xx_reg_table.h> <lan80xx_regs.h>
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ENTRY_RE = re.compile(
    r'\{\s*"(LAN80XX_[A-Z0-9_]+)"\s*,\s*'
    r"0x([0-9A-Fa-f]+)U\s*,\s*"      # mmd
    r"([01])U\s*,\s*"               # is32
    r"0x([0-9A-Fa-f]+)U\s*\}"       # addr
)

MMD_MAX = 0x20  # mmd is 5-bit

# Human-readable name + one-line note per MMD number. Kept in one place
# so the generated header documents the address map.
MMD_INFO = {
    0x01: ("LINE_PMA",     "line PMA/PMD (+ slice / RS-FEC / PCS / SFP)"),
    0x03: ("MAC_LINE_PCS", "host+line MAC, line PCS/PCS25G"),
    0x07: ("LINE_KR",      "line auto-neg / KR"),
    0x08: ("MACSEC_A",     "MACsec instance A"),
    0x09: ("HOST_PMA",     "host PMA/PMD (+ packet-BIST / slice / RS-FEC / PCS)"),
    0x0A: ("PTP",          "1588 TSU"),
    0x0B: ("HOST_PCS",     "host PCS / PCS25G"),
    0x0F: ("HOST_KR",      "host auto-neg / KR"),
    0x1E: ("GLOBAL",       "MCU mailbox, cross-connect, clk, gpio, PTP-global"),
    0x1F: ("MACSEC_B",     "MACsec instance B"),
}


def parse(table_path: Path) -> dict[int, list[tuple[int, str]]]:
    """Returns {mmd: [(addr, name), ...]} in address order."""
    by_mmd: dict[int, list[tuple[int, str]]] = {}
    for line in table_path.read_text().splitlines():
        m = ENTRY_RE.search(line)
        if not m:
            continue
        name, mmd, _is32, addr = m.groups()
        mmd_i = int(mmd, 16)
        if mmd_i >= MMD_MAX:
            sys.stderr.write(f"skipping out-of-range mmd 0x{mmd_i:X} ({name})\n")
            continue
        by_mmd.setdefault(mmd_i, []).append((int(addr, 16), name))
    for regs in by_mmd.values():
        regs.sort(key=lambda r: (r[0], r[1]))
    return by_mmd


def mmd_label(mmd: int) -> str:
    return MMD_INFO.get(mmd, (f"MMD_{mmd:02X}", "unclassified"))[0]


def emit(out_path: Path, src_name: str,
         by_mmd: dict[int, list[tuple[int, str]]]) -> None:
    L: list[str] = [
        "// Copyright (c) 2026 Vincent Jardin, Vincent Cruz, Free Mobile",
        "// SPDX-License-Identifier: BSD-4-Clause",
        "//",
        f"// Auto-generated by gen_lan80xx_regs_header.py from {src_name}.",
        "// Do not edit by hand; re-run the generator instead.",
        "//",
        "// Symbolic enums for the LAN80xx MDIO Manageable Devices (MMDs)",
        "// and their register address offsets. Enumerator values are the",
        "// raw offsets; combine with an mmd to form an SPI address.",
        "",
        "#ifndef LAN80XX_REGS_H",
        "#define LAN80XX_REGS_H",
        "",
        "/* MDIO Manageable Devices (the mmd field of an SPI instruction). */",
        "typedef enum {",
    ]
    for mmd in sorted(by_mmd):
        name, note = MMD_INFO.get(mmd, (f"MMD_{mmd:02X}", "unclassified"))
        L.append(f"    LAN80XX_MMD_{name:<13} = 0x{mmd:02X}, /* {note} */")
    L += [
        "} lan80xx_mmd_t;",
        "",
    ]

    seen: dict[str, tuple[int, int]] = {}  # name -> (mmd, addr) already emitted
    for mmd in sorted(by_mmd):
        label = mmd_label(mmd)
        L.append(f"/* MMD 0x{mmd:02X} {label} -- register offsets. */")
        L.append(f"enum lan80xx_reg_{label.lower()} {{")
        for addr, name in by_mmd[mmd]:
            prev = seen.get(name)
            if prev is not None:
                if prev != (mmd, addr):
                    sys.stderr.write(
                        f"warning: {name} redefined "
                        f"(0x{prev[0]:02X}:0x{prev[1]:04X} vs "
                        f"0x{mmd:02X}:0x{addr:04X}); keeping first\n"
                    )
                continue
            seen[name] = (mmd, addr)
            L.append(f"    {name} = 0x{addr:04X},")
        L.append("};")
        L.append("")

    L += [
        "#endif /* LAN80XX_REGS_H */",
        "",
    ]
    out_path.write_text("\n".join(L))


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        sys.stderr.write(__doc__ or "")
        return 2
    src = Path(argv[1])
    out = Path(argv[2])
    if not src.exists():
        sys.stderr.write(f"input table not found: {src}\n")
        return 1
    by_mmd = parse(src)
    if not by_mmd:
        sys.stderr.write(f"no register entries parsed from {src}\n")
        return 1
    emit(out, src.name, by_mmd)
    total = sum(len(v) for v in by_mmd.values())
    sys.stderr.write(
        f"emitted {total} register offsets across {len(by_mmd)} MMDs to {out}\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
