name: ClusterFuzzLite PR fuzzing
on:
  pull_request:
    branches: [main]
permissions: read-all
jobs:
  PR:
    runs-on: ubuntu-latest
    concurrency:
      group: cflite-pr-${{ github.ref }}-${{ matrix.sanitizer }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]
    steps:
      - name: Build fuzzers (${{ matrix.sanitizer }})
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: c
          sanitizer: ${{ matrix.sanitizer }}
      - name: Run fuzzers (${{ matrix.sanitizer }})
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          mode: code-change
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true
